<ips:template parameters="" />
<section>
	<p class='ipsMessage ipsMessage_warning'>Your community suite data or database configuration is saved in an encoding other than UTF-8.  Before your site can be upgraded to the 4.0.0 Community Suite, we must convert the encoding to UTF-8.</p>
</section>

<div class='ipsPad_double ipsType_center'>
	<a href='../convertutf8' class='ipsButton ipsButton_large ipsButton_primary'>Convert character set</a>
</div>