<ips:template parameters="$requirements, $designerMode" />
{{$canProceed = TRUE;}}
<section>
	{{if $designerMode}}
		<h2 class="ipsType_sectionHead">Designers' Mode On</h2>
		<ul class="ipsPad ipsType_large ipsList_checks">
			{{$canProceed = FALSE;}}
			<li class="fail inline">
				Designers' Mode is currently enabled.
			</li>
			<li class='ipsType_normal'>
				<a href="{url="controller=systemcheck&key={$_SESSION['uniqueKey']}&disableDesignersMode=1"}" class="ipsButton ipsButton_negative">Disable Designers' Mode now</a>
				<div class='ipsType_light ipsType_small'>Disabling Designers' Mode now will <strong>not</strong> synchronize your templates.<br>If you need to save your edited files, please synchronize them via the ACP &gt; Customization &gt; Themes before disabling Designer's Mode.</div>
			</li>
		</ul>
	{{endif}}
	{{foreach $requirements['requirements'] as $k => $_requirements}}
		<h2 class="ipsType_sectionHead">{$k} Requirements</h2>
		<ul class="ipsPad ipsType_large ipsList_checks">
			{{foreach $_requirements as $item}}
				{{if !$item['success']}}{{$canProceed = FALSE;}}{{endif}}
				<li class="{{if $item['success']}}success{{else}}fail{{endif}}">{$item['message']}</li>
			{{endforeach}}
		</ul>
	{{endforeach}}
	{{if isset( $requirements['advice'] ) and count( $requirements['advice'] )}}
		<h2 class="ipsType_sectionHead">Advice</h2>
		<br><br>
		<p class="ipsType_normal">None of these items are required in order to continue with the upgrade. However, for the best experience, you may want to make a note of them and contact your hosting provider or system administrator after the upgrade to consider them. You can re-run these checks later from the <em>Support</em> section of the Administrator Control Panel.</p>
		<ul class="ipsPad ipsType_large ipsList_checks">
			{{foreach $requirements['advice'] as $item}}
				<li class="advisory">{$item}</li>
			{{endforeach}}
		</ul>
	{{endif}}
</section>

<div class='ipsPad_double ipsType_center'>
	{{if $canProceed}}
		<a href='{url="controller=license&key={$_SESSION['uniqueKey']}"}' class='ipsButton ipsButton_large ipsButton_primary'>Continue</a>
	{{else}}
		<a href='' class='ipsButton ipsButton_large ipsButton_primary ipsButton_disabled'>You must correct any issues listed above before you can proceed</a>
	{{endif}}
</div>