<ips:template parameters="$title,$html,$initError=FALSE,$path=null" />
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{$title}</title>
		<link rel='stylesheet' href='css/reset.css' media='all'>
		<link rel='stylesheet' href='css/fonts.css' media='all'>
		<link rel='stylesheet' href='css/global.css' media='all'>
		<link rel='stylesheet' href='css/layout.css' media='all'>
		<link rel='stylesheet' href='css/messages.css' media='all'>
		<link rel='stylesheet' href='css/misc.css' media='all'>
		<link rel='stylesheet' href='css/forms.css' media='all'>
		<link rel='stylesheet' href='css/typography.css' media='all'>
		<link rel='stylesheet' href='css/buttons.css' media='all'>
		<link rel='stylesheet' href='css/installer.css' media='all'>
		<script type="text/javascript">
			var IPS_TIMEOUT = 30;
		</script>
		<script src="js/jquery.min.js"></script>
		<script src="js/multipleRedirect.js"></script>
	</head>
	<body class='ipsApp ipsApp_installer'>
		
		<div id='elInstaller_wrap'>
			<div id='ipsLayout_header' class='ipsClearfix' role='banner'>
				<header>
					<a href='/' id='elSiteTitle'><span id='elLogo'><img src='img/logo.png' alt=''></span> Upgrade IPS Community Suite 4</a>
				</header>
			</div>
			<main id='elInstaller_body'>
				{{if !$initError and ( ( \IPS\Dispatcher::i()->step != 1 AND \IPS\Dispatcher::i()->step != 8 ) || \IPS\Request::i()->start )}}
					<div class='ipsPad ipsAreaBackground_light'>
						<h1 class='ipsType_pageTitle'>
							{lang="step" sprintf="\IPS\Dispatcher::i()->step ?: 1"}: {$title}
						</h1>
					</div>
					<div class='ipsColumns ipsPad'>
						<div class='ipsColumn ipsColumn_wide ipsPad' id='elInstaller_stepsWrap'>
							<ul id='elInstaller_steps'>
								{{foreach array( 1 => 'Login', 2 => 'System Check', 3 => 'License', 4 => 'Applications', 5 => 'Upgrade Options', 6 => 'Confirm', 7 => 'Upgrade' ) as $i => $lang}}
									<li class='{{if \IPS\Dispatcher::i()->step == $i}}elInstaller_stepActive{{elseif \IPS\Dispatcher::i()->step > $i}}elInstaller_stepDone{{endif}}'>
										<i class='{{if \IPS\Dispatcher::i()->step == $i or ( !\IPS\Dispatcher::i()->step and $i == 1 )}}fa fa-circle{{elseif \IPS\Dispatcher::i()->step > $i}}fa fa-check{{else}}fa fa-circle-o{{endif}}'></i>&nbsp;&nbsp;{$lang}
									</li>
								{{endforeach}}
							</ul>
						</div>
						<div class='ipsColumn ipsColumn_fluid'>
							<div class='ipsPad'>
								{$html|raw}
							</div>
						</div>
					</div>
				{{elseif \IPS\Request::i()->controller === 'done'}}
					<div class='ipsPad_double ipsType_center'>
						<h1 class='ipsType_pageTitle' id='elInstaller_welcome'>Your IPS Community Suite 4 is ready</h1>
						<p class='ipsType_normal ipsType_light'>
							{lang="upgrade_complete"}
						</p>
						<br><br>
						<a href='{expression="\IPS\Settings::i()->base_url"}' class='ipsButton ipsButton_large ipsButton_primary'>Go to the suite</a>
						<br><br>
						<a href="{expression="\IPS\Http\Url::ips('docs/docs')"}" target="_blank">Suite Documentation</a>
					</div>
				{{else}}
					<div class='ipsPad_double ipsType_center'>
						<h1 class='ipsType_pageTitle' id='elInstaller_welcome'>Welcome to IPS Community Suite 4</h1>
						<p class='ipsType_normal ipsType_light'>
							{{if $initError}}
								{$initError}
							{{else}}
								This process will install your software for you. Be sure you have your license key and MySQL database details to hand.
							{{endif}}
						</p>
						{{if !$initError}}
							<br><br>
							<a href='{url="&start=1"}' class='ipsButton ipsButton_large ipsButton_primary'>Start Upgrade</a>
						{{endif}}
						<br><br>
						<a href="{expression="\IPS\Http\Url::ips('docs/install_guide')"}" target="_blank">Install Guide</a>
					</div>
				{{endif}}
			</main>
		</div>
	</body>
</html>