<ips:template parameters="$json, $time" />
<section>
	<h2 class="ipsType_sectionHead">{lang="upgrade_unfinished"}</h2>
	<ul class="ipsPad ipsType_large ipsList_checks">
		<li class="advisory">You have an unfinished upgrade from {datetime="$time" norelative="true"}</li>
		<li>
			<strong>{lang="upgrade_applications"}</strong>
			<ul>
				{{foreach( $json['session']['apps'] ) as $app}}
					<li>{expression="ucfirst( $app )"}</li>
				{{endforeach}}
			</ul>
		</li>
		<li>
			<strong>{lang="upgrade_status"}</strong>
			<ul>
				<li>{lang="status"}: {$json['step']}</li>
				<li>{lang="application"}: {{if isset( $json['data'][1] )}}{$json['data'][1]}{{else}}<em>Not set</em>{{endif}}
				<li>{lang="current_version"}: {{if isset( $json['data']['extra']['_current'] )}}{$json['data']['extra']['_current']}{{else}}<em>Not set</em>{{endif}}
			</ul>
		</li>
	</ul>
</section>
<div class='ipsPad_double ipsType_center'>
	<a href='{url="controller=continueupgrade&key={$_SESSION['uniqueKey']}"}' class='ipsButton ipsButton_large ipsButton_primary ipsButton_positive'>Continue Upgrade</a>
	<a href='{url="controller=systemcheck&key={$_SESSION['uniqueKey']}&skippreviousupgrade=1"}' class='ipsButton ipsButton_large ipsButton_primary'>Start Fresh Upgrade</a>
</div>